### ISSUE TITLE
关于AMM模块

### ISSUE THREAD

**Issue by SeeU1119** [DateBro/PSGAN-PyTorch#1]
十分感谢分享的代码，这个PSGAN我在前几个月做尝试复现过，但是对于文中所描述的AMM模块也表示有点怀疑，发现实验下来效果不是很好，尤其对于生成的图像经常会出现奇奇怪怪的伪影，我在想你有没有试验过这个模块， 结果如何？

**Comment by DateBro** [comment]
AMM模块要用68 landmakrs的detector，我看那篇论文里提到的是10个landmarks，网上找的github也实现的是10个，暂时没想好怎么实现这里；PSGAN说attention要用semantic map缩放后相同语义的像素，我觉得这里有点奇怪，毕竟feature map和原图的像素也不能那么对应，也还没做。现在实现的只是两个feature map的attention，但效果看着已经确实比BeautyGAN好很多了，BeautyGAN的结果当pose差别比较大的时候，伪影还是挺严重的，我觉得attention机制确实有效。

**Comment by SeeU1119** [comment]
谢谢 现在就等着作者放出源码了 总觉得这个AMM怪怪的

**Comment by DateBro** [comment]
作者说五月放代码，我也一直挺期待的 🤣
